# Generated by Django 4.2.9 on 2024-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_company_customer_clinic_or_hosbital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS'), ('DR', 'DR')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
