# Generated by Django 4.2.9 on 2024-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_title_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestClinicSystemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clinic_count', models.PositiveIntegerField()),
                ('departement_count', models.PositiveIntegerField()),
                ('doctors_count', models.PositiveIntegerField()),
                ('users_count', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHospitalSystemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('hosbital', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hospital_beds_count', models.PositiveIntegerField()),
                ('departement_count', models.PositiveIntegerField()),
                ('doctors_count', models.PositiveIntegerField()),
                ('users_count', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
