# Generated by Django 4.2.9 on 2024-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_requestclinicsystempackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_contact_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF')], default='TEXT', max_length=10),
        ),
    ]
