# Generated by Django 4.2.9 on 2024-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
    ]
