# Generated by Django 4.2.9 on 2024-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_to_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
