# Generated by Django 4.2.9 on 2024-03-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0008_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigend_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
