# Generated by Django 4.2.9 on 2024-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customer_added_by_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
    ]
